# require to set
# server-name: 'server'
debug: false

host: 'localhost'
port: 6379
password: ''
channel: 'opak:luckperms'

# Player sync option
sync-player-rank: true
sync-player-prefix: false
sync-player-suffix: false
sync-player-permission: false

enable-listener: false